### ISSUE TITLE
Trouble understanding why subs map gets deleted entirely upon remaining element count = 1

### ISSUE THREAD

**Issue by tshi206** [btvoidx/mint#4]
https://github.com/btvoidx/mint/blob/6c4a9741de82075c7574c578f9bcfeffd6652932/context/mint.go#L103

sorry if this is intended but i really don't understand the underlying idea behind this, should it be like `if len(e.subs[key[T]{}]) == 0 {` instead?

```
package main

import (
	"fmt"
	"time"

	"github.com/btvoidx/mint"
)

func main() {
	e := &mint.Emitter{}
	type A = string
	off := mint.On[A](e, func(s string) {
		fmt.Println("Hello World", s)
	})

	mint.On[A](e, func(s string) {
		fmt.Println("Bye World", s)
	})

	mint.Emit[A](e, "foo")

	time.Sleep(5 * time.Second)

	off()

	time.Sleep(5 * time.Second)

	mint.Emit[A](e, "bar")

	time.Sleep(5 * time.Second)

	fmt.Println("???")
}

```

Not sure if I understand your code correctly but I was expecting another 'Bye World bar' since I only `off` the first listener.

If I dump the above into the playground I get:
```
OUTPUT


Bye World foo
Hello World foo
???

Program exited.
```

**Comment by btvoidx** [comment]
Uhh, yep. That is a problem. Thank you so much for catching that. Tests are passing, so I never noticed. Will fix.

I guess at some point I wanted to delete the map straight away if it had only one key remaining, but got it mixed up.
