### ISSUE TITLE
What are the generics for here?

### ISSUE THREAD

**Issue by viters** [btvoidx/mint#5]
Pardon, I might be missing something and it is also not an attack, it is just my curiosity. 

It is stated in docs "Type safe: built on generics", and indeed I see that `Emit` and `On` are generic - but what does it actually change? As`Emitter` is not generic, you can effectively `Emit` any type of data and listen to any type of data, there is no guard that you will be listening to types that are actually sent over emitter. I do not see the difference to `Emit` and `On` having `any` instead of `T`.

**Comment by btvoidx** [comment]
Active subscribers are stored in a map with a key of type `struct[T]{}`, and these structs compare unequal if they have different `T`s, even though they have identical fields (none), and therefore can be used as map keys inside a `map[any]...`. This is the trick that allows `Emit[T]` to only call those subscribers, which subscribed with the same `T`. Calling `Emit[any]` will notify only `any` subscribers, and `On[any]` will subscribe only to `Emit[any]`s and will not receive any other emits.

Hope this clears things up a bit.

**Comment by viters** [comment]
@btvoidx Awesome, thanks for clarification! Let me thank you with a star.
